### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/compasstools#18]
@selinalcheng Design + plot tables can have multiple dataloggers...do you assume that all have matched timestamps? Do you round timestamps before doing data merges? Or something else?

Thanks, b

**Comment by selinalcheng** [comment]
What do you mean by matched timestamps? Like data are collected at the same intervals? The way our code is written right now, the user has to specify the time increment for the data as an argument in the joining ("normalization") function. We then round all timestamps to the specified time increment for that LoggerNet table. Is this what you were asking?

**Comment by bpbond** [comment]
Sorry if I wasn't clear. Yes, that's exactly my question. Thank you!

**Comment by selinalcheng** [comment]
Oh ok, great! And to clarify -- because different LoggerNet tables have different increments, we are currently processing them sort of piecewise. Tables with different increments need to be processed separately, which is why I separated the tables into different directories. Figuring out the time increment can definitely just be coded into the function, though -- I'm working on code for that in case Roy wants to implement it.

**Comment by bpbond** [comment]
Yeah, the more I thought about it—for all kinds of reasons including timestamps, I agree, tables have to be processed one-by-one. Thank you!
